{% set name = "quimb" %}
{% set version = "1.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/quimb-{{ version }}.tar.gz
  sha256: 2ca0ddbc650b0fe33154e427e77c6405c572614c61d51e08c55aca7d47fbf0e1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.6
    - setuptools >=45
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.6
    - numpy >=1.17
    - scipy >=1.0.0
    - numba >=0.39
    - psutil >=4.3.1
    - cytoolz >=0.8.0
    - tqdm >=4
    - autoray >=0.6.7
    - cotengra >=0.5.6

test:
  imports:
    - quimb
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://quimb.readthedocs.io
  summary: Quantum information and many-body library.
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jcmgray
    - jan-janssen
