{% set name = "quimb" %}
{% set version = "1.12.1" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/quimb-{{ version }}.tar.gz
  sha256: fe2dc4d03eecd372bc8344b6f33228f9c7d4da208bb8e89810846ab40fd9795c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.17
    - scipy >=1.16.0
    - numba >=0.39
    - psutil >=4.3.1
    - cytoolz >=0.8.0
    - tqdm >=4
    - autoray >=0.8
    - cotengra >=0.7.1

test:
  imports:
    - quimb
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://quimb.readthedocs.io
  summary: Quantum information and many-body library.
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jcmgray
    - jan-janssen
