{% set name = "quimb" %}
{% set version = "1.11.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/quimb-{{ version }}.tar.gz
  sha256: 12546651f714e4ff3adb53dc7b620b4c4eb3fd8d8aafad0f92ac4cc04f03440c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.17
    - scipy >=1.0.0
    - numba >=0.39
    - psutil >=4.3.1
    - cytoolz >=0.8.0
    - tqdm >=4
    - autoray >=0.6.12
    - cotengra >=0.7.1

test:
  imports:
    - quimb
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://quimb.readthedocs.io
  summary: Quantum information and many-body library.
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jcmgray
    - jan-janssen
