{% set name = "quimb" %}
{% set version = "1.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/quimb-{{ version }}.tar.gz
  sha256: f5a769e0403094f4fbccd9833648e48e7fac209a43b329b0586e7c4332a1b963

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >=3.6
    - numpy >=1.17
    - scipy >=1.0.0
    - numba >=0.39
    - psutil >=4.3.1
    - cytoolz >=0.8.0
    - tqdm >=4
    - autoray >=0.6.12
    - cotengra >=0.6.1

test:
  imports:
    - quimb
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://quimb.readthedocs.io
  summary: Quantum information and many-body library.
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jcmgray
    - jan-janssen
